### ISSUE TITLE
No warning and error messages

### ISSUE THREAD

**Issue by neospyk** [vieron/stylelint-webpack-plugin#50]
Hello!

There are no informative messages in console about error.
For now I can see just 
`
Error: Failed because of a stylelint error.
at linterSuccess (...somePath/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:28:14)
`
But in version 0.4.0 were detailed error messages 
` 13:12  ✖  Unexpected whitespace before ";"   declaration-block-semicolon-space-before
`
I think problem is in run-compilation.js:
In version 0.4.0:
`    if (!options.quiet) {
        console.log(chalk.yellow(options.formatter(lint.results)));
      }
`
But now this code is removed.

**Comment by samrap** [comment]
Can this be tagged in an 0.4.3 bug fix release please?

**Comment by JaKXz** [comment]
@samrap I apologise for the delay - I should have released a patch version right away. I was hoping to get some new features into a v0.5 release, and one of two is done :) 

If you're willing, you can use `stylelint-webpack-plugin#master` and open any issues you see with it. Otherwise you can use v0.4.3 tag. 

I'll be releasing a new version soon - just had an (non-code) emergency to deal with last night. Appreciate your patience.

**Comment by JaKXz** [comment]
`+ stylelint-webpack-plugin@0.5.0` published!

**Comment by samrap** [comment]
Awesome! Thanks for all your hard work, this plugin is great!
