### ISSUE TITLE
options: "files" throwing errors when passed basic string input, unable to find app root directory

### ISSUE THREAD

**Issue by sdtsui** [vieron/stylelint-webpack-plugin#7]
Hi there,

1. Running `stylelint '**/*.css'` in CLI works as expected. 
2. Configuring it through this package does not seem to get any matches. For all of the commented-out patterns I've tried (see the gist), I get:
`Error: Files glob patterns specified did not match any files`
3. The only exception to point 2 is '../../**/*.css'; this path begins to lint css in the `node_modules` folder. 
If I try to go one level up, I get:
 a `EISDIR: illegal operation on a directory, read`.
4. I get the same effect for all cases if I remove the `configBaseddir`, and `configFile` configuration properties.

This might be multiple separate errors. It looks like something is wrong with the way `files` is sending the glob pattern, and we're stuck searching for matches over contents of the `stylelint` folder, instead of the directory we want. In addition, when we go up enough levels, the plugin seems to be trying to access directories as files (point 4).

What do you think?
`webpack.config.js` below: 
https://gist.github.com/sdtsui/feb5f1de7c7c53e6e42180f201d890cd

Thanks!

p.s. for completeness, here is my `package.json`, with the `lint-css` script that works.
https://gist.github.com/sdtsui/a16a054228999f9150bb0fadc6f6d647
I'm on Node `v5.5.0`.

**Comment by sdtsui** [comment]
forgot to name issue. closed and re-opened.

**Comment by vieron** [comment]
Hi @sdtsui 

I see some things that could cause the problem:

- You shouldn't set `options.context` to `'inherits from webpack'`. You should specify a base path, or nothing and the plugin will take the path from the webpack [context](https://webpack.github.io/docs/configuration.html#context). 
Sorry because the readme is not clear enough.

- If you want to lint scss, you should also set the `syntax` option to `scss` (http://stylelint.io/user-guide/node-api/#syntax)

- Also, `configBasedir` is not a valid option.

Let me know if that fix the problem.

**Comment by sdtsui** [comment]
@vieron Thanks! Makes sense -- wasn't thinking about `options.context`.

**Comment by yoyurec** [comment]
>You shouldn't set options.context to 'inherits from webpack'. 
why don't you just delete(/comment/etc) it from options example on README so devs will not be confused?
